<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="\\SRV01\users%24\rjohnson\My Documents\appsettings.json" Link="appsettings.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.13" />
    <PackageReference Include="Microsoft.Identity.Web" Version="2.5.0" />
    <PackageReference Include="Serilog" Version="2.10.0" />
	  <PackageReference Include="Serilog.Enrichers.Environment" Version="2.2.0" />
	  <PackageReference Include="Serilog.Enrichers.Process" Version="2.0.2" />
	  <PackageReference Include="Serilog.Enrichers.Thread" Version="3.1.0" />
	  <PackageReference Include="Serilog.Extensions.Hosting" Version="4.2.0" />
	  <PackageReference Include="Serilog.Settings.Configuration" Version="3.3.0" />
	  <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
	  <PackageReference Include="Serilog.Sinks.Email" Version="2.4.0" />
	  <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NBC.Authorization\NBC.Authorization.csproj" />
    <ProjectReference Include="..\RefreshNorthcrestDataFromPlanningCenter.Data\RefreshNorthcrestDataFromPlanningCenter.Data.csproj" />
    <ProjectReference Include="..\RefreshNorthcrestDataFromPlanningCenter.Domain\RefreshNorthcrestDataFromPlanningCenter.Domain.csproj" />
  </ItemGroup>

</Project>
