// <auto-generated />
using System;
using FellowshipOne.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FellowshipOne.Data.Migrations
{
    [DbContext(typeof(FellowshipOneDbContext))]
    [Migration("20240705145646_modify-address-type-column")]
    partial class modifyaddresstypecolumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Northcrest.Domain.FellowshipOne.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("Address1")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Address2")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Address3")
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("AddressDate")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("City")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Country")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("County")
                        .HasColumnType("varchar(200)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("varchar(20)");

                    b.HasKey("AddressId");

                    b.HasIndex("PersonId");

                    b.ToTable("Addresses", (string)null);
                });

            modelBuilder.Entity("Northcrest.Domain.FellowshipOne.BackgroundCheck", b =>
                {
                    b.Property<int>("BackgroundCheckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BackgroundCheckId"));

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(20)");

                    b.Property<int>("TrackingNumber")
                        .HasColumnType("int");

                    b.HasKey("BackgroundCheckId");

                    b.HasIndex("PersonId");

                    b.ToTable("BackgroundChecks", (string)null);
                });

            modelBuilder.Entity("Northcrest.Domain.FellowshipOne.Communication", b =>
                {
                    b.Property<int>("CommunicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommunicationId"));

                    b.Property<string>("Comment")
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("GeneralType")
                        .HasColumnType("varchar(20)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<bool>("Preferred")
                        .HasColumnType("bit");

                    b.Property<string>("SearchValue")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SpecificType")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Value")
                        .HasColumnType("varchar(50)");

                    b.HasKey("CommunicationId");

                    b.HasIndex("PersonId");

                    b.ToTable("Communications", (string)null);
                });

            modelBuilder.Entity("Northcrest.Domain.FellowshipOne.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<string>("Comment")
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(20)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("EventId");

                    b.HasIndex("PersonId");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("Northcrest.Domain.FellowshipOne.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Denomination")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Employer")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("FellowshipOneId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("FirstRecordDate")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("FormerChurch")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FormerName")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Gender")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("GoesByName")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("HouseholdId")
                        .HasColumnType("int");

                    b.Property<string>("HouseholdMemberType")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ImageFilePath")
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("LastMatchDate")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("LastName")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("OccupationDescription")
                        .HasColumnType("varchar(300)");

                    b.Property<string>("OccupationName")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Salutation")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("School")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("StatusComment")
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("StatusDate")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Substatus")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Suffix")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Title")
                        .HasColumnType("varchar(100)");

                    b.HasKey("PersonId");

                    b.ToTable("Persons", (string)null);
                });

            modelBuilder.Entity("Northcrest.Domain.FellowshipOne.Address", b =>
                {
                    b.HasOne("Northcrest.Domain.FellowshipOne.Person", "Person")
                        .WithMany("Addresses")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Northcrest.Domain.FellowshipOne.BackgroundCheck", b =>
                {
                    b.HasOne("Northcrest.Domain.FellowshipOne.Person", "Person")
                        .WithMany("BackgroundChecks")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Northcrest.Domain.FellowshipOne.Communication", b =>
                {
                    b.HasOne("Northcrest.Domain.FellowshipOne.Person", "Person")
                        .WithMany("Communications")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Northcrest.Domain.FellowshipOne.Event", b =>
                {
                    b.HasOne("Northcrest.Domain.FellowshipOne.Person", "Person")
                        .WithMany("Events")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Northcrest.Domain.FellowshipOne.Person", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("BackgroundChecks");

                    b.Navigation("Communications");

                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
