// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RefreshNorthcrestDataFromPlanningCenter.Data;

#nullable disable

namespace RefreshNorthcrestDataFromPlanningCenter.Data.Migrations
{
    [DbContext(typeof(NorthcrestDbContext))]
    [Migration("20221206172257_addSongAttachmentsTable")]
    partial class addSongAttachmentsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RefreshNorthcrestDataFromPlanningCenter.Domain.Attachment", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachmentId"), 1L, 1);

                    b.Property<string>("ContentType")
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Downloadable")
                        .HasColumnType("bit");

                    b.Property<byte[]>("File")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("FileSize")
                        .HasColumnType("int");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<bool>("HasPreview")
                        .HasColumnType("bit");

                    b.Property<int>("SermonId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("varchar(5000)");

                    b.HasKey("AttachmentId");

                    b.HasIndex("SermonId");

                    b.ToTable("Attachments", (string)null);
                });

            modelBuilder.Entity("RefreshNorthcrestDataFromPlanningCenter.Domain.GeneralSong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ArrangementId")
                        .HasColumnType("int");

                    b.Property<string>("ArrangementName")
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Author")
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Copyright")
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime>("LastScheduledDateTime")
                        .HasColumnType("datetime2(7)");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.Property<string>("SongName")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Themes")
                        .HasColumnType("varchar(2000)");

                    b.HasKey("Id");

                    b.ToTable("GeneralSongs", (string)null);
                });

            modelBuilder.Entity("RefreshNorthcrestDataFromPlanningCenter.Domain.Plan_ForSongs", b =>
                {
                    b.Property<int>("Plan_ForSongsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Plan_ForSongsId"), 1L, 1);

                    b.Property<DateTime>("PlanDateTime")
                        .HasColumnType("datetime2(7)");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Plan_ForSongsId");

                    b.ToTable("Plan_ForSongs", (string)null);
                });

            modelBuilder.Entity("RefreshNorthcrestDataFromPlanningCenter.Domain.PlanSong", b =>
                {
                    b.Property<int>("PlanSongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanSongId"), 1L, 1);

                    b.Property<int>("ArrangementId")
                        .HasColumnType("int");

                    b.Property<string>("ArrangementName")
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Author")
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Copyright")
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("KeyName")
                        .HasColumnType("varchar(25)");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("varchar(5000)");

                    b.Property<int>("Plan_ForSongsId")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.Property<string>("SongName")
                        .HasColumnType("varchar(500)");

                    b.HasKey("PlanSongId");

                    b.HasIndex("Plan_ForSongsId");

                    b.ToTable("PlanSongs", (string)null);
                });

            modelBuilder.Entity("RefreshNorthcrestDataFromPlanningCenter.Domain.Sermon", b =>
                {
                    b.Property<int>("SermonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SermonId"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("varchar(5000)");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SermonDateTime")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Speaker")
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Title")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Type")
                        .HasColumnType("varchar(50)");

                    b.HasKey("SermonId");

                    b.ToTable("Sermons", (string)null);
                });

            modelBuilder.Entity("RefreshNorthcrestDataFromPlanningCenter.Domain.SongAttachment", b =>
                {
                    b.Property<int>("SongAttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SongAttachmentId"), 1L, 1);

                    b.Property<string>("ContentType")
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Downloadable")
                        .HasColumnType("bit");

                    b.Property<byte[]>("File")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FilePath")
                        .HasColumnType("varchar(500)");

                    b.Property<int>("FileSize")
                        .HasColumnType("int");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<bool>("HasPreview")
                        .HasColumnType("bit");

                    b.Property<int>("PlanSongId")
                        .HasColumnType("int");

                    b.Property<int>("SermonId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("varchar(5000)");

                    b.HasKey("SongAttachmentId");

                    b.HasIndex("PlanSongId");

                    b.ToTable("SongAttachments", (string)null);
                });

            modelBuilder.Entity("RefreshNorthcrestDataFromPlanningCenter.Domain.SongNote", b =>
                {
                    b.Property<int>("SongNoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SongNoteId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Content")
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("PlanSongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("SongNoteId");

                    b.HasIndex("PlanSongId");

                    b.ToTable("SongNotes", (string)null);
                });

            modelBuilder.Entity("RefreshNorthcrestDataFromPlanningCenter.Domain.Attachment", b =>
                {
                    b.HasOne("RefreshNorthcrestDataFromPlanningCenter.Domain.Sermon", "Sermon")
                        .WithMany("Attachments")
                        .HasForeignKey("SermonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sermon");
                });

            modelBuilder.Entity("RefreshNorthcrestDataFromPlanningCenter.Domain.PlanSong", b =>
                {
                    b.HasOne("RefreshNorthcrestDataFromPlanningCenter.Domain.Plan_ForSongs", "Plan_ForSongs")
                        .WithMany("PlanSongs")
                        .HasForeignKey("Plan_ForSongsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan_ForSongs");
                });

            modelBuilder.Entity("RefreshNorthcrestDataFromPlanningCenter.Domain.SongAttachment", b =>
                {
                    b.HasOne("RefreshNorthcrestDataFromPlanningCenter.Domain.PlanSong", "PlanSong")
                        .WithMany("SongAttachments")
                        .HasForeignKey("PlanSongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanSong");
                });

            modelBuilder.Entity("RefreshNorthcrestDataFromPlanningCenter.Domain.SongNote", b =>
                {
                    b.HasOne("RefreshNorthcrestDataFromPlanningCenter.Domain.PlanSong", "PlanSong")
                        .WithMany("SongNotes")
                        .HasForeignKey("PlanSongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanSong");
                });

            modelBuilder.Entity("RefreshNorthcrestDataFromPlanningCenter.Domain.Plan_ForSongs", b =>
                {
                    b.Navigation("PlanSongs");
                });

            modelBuilder.Entity("RefreshNorthcrestDataFromPlanningCenter.Domain.PlanSong", b =>
                {
                    b.Navigation("SongAttachments");

                    b.Navigation("SongNotes");
                });

            modelBuilder.Entity("RefreshNorthcrestDataFromPlanningCenter.Domain.Sermon", b =>
                {
                    b.Navigation("Attachments");
                });
#pragma warning restore 612, 618
        }
    }
}
